### ISSUE TITLE
Add gadget UI, wrong and missing texts for Geta.Categories

### ISSUE THREAD

**Issue by alasvant** [Geta/EpiCategories#10]
As the Geta.Categories can be added as a gadget in Episerver UI when adding it the dialog displays wrong texts (seems some random text inherited by some convention).

![add-geta-categories-gadget](https://user-images.githubusercontent.com/22050586/43827615-f103e6c4-9b02-11e8-9662-6196b3fb423c.PNG)

The CategoryTreeComponent only overrides the title but not the description property (as seen in the pic, missing text).

May I suggest that you put the title and description texts to your language file (and add the missing description text). This way it would be easier to localize in projects that want to use languages that you don't have localizations for. I would have the title as "Geta Categories" as it would be clear to users VS currently it is using Episerver CMS categories title (which could change and for example currently there is a bug in Finnish text (currently in Finnish "Muokkaa kohdetta {0}", which means edit target 0 the placeholder ;) )

Looking at the sources in GitHub it looks like these sources are not the ones that has been used to built the Episerver NuGet feed package? Latest sources are not available here? Based on this when looking at the geta.epicategories.xml file for example it has Finnish localizations but the file in GitHub doesn't. Just asking ;)

**Comment by MattisOlsson** [comment]
I fixed this issue now. Version 1.2.5 should be available on Episerver NuGet feed in the next few days. 1.2.5 will also bring another change: Client resources for the module is now packaged in a .zip file with a version folder to avoid caching issues when updating to latest version. I recommend deleting everything in the ~/modules/_protected/geta-epicategories except the zip file after updating to 1.2.5.

However, I don't want the default title to be Geta Categories since it takes up more space. But it's possible to change the language XML file now at least to fit your needs. :) Finnish localization has never existed for this module. It is not in the NuGet feed package either so it must have been added manually by some developer in your project.

**Comment by alasvant** [comment]
I shouldn't go around making "blames" before checking own source control for changes in the "geta.epicategories.xml" I just assumed that all our devs would have known not to edit NuGet package provided files but instead create a new file to localize or to override something. So sorry ;)

You are right on the too long text. I could submit you the Finnish localizations if you would like to have those (translations from your current en/sv/no texts)?

**Comment by MattisOlsson** [comment]
Yes, please add Finnish localization!
