### ISSUE TITLE
IE11 script error

### ISSUE THREAD

**Issue by Sonesson** [Geta/EpiCategories#12]
CategorySelector.js fails at line 80: postMixInProperties (), saying it expects a ":" when switching to properties view in episerver 11 CMS edit mode.

I tried patching the file to
postMixInProperties: function ()
but that led to other DOM errors.

**Comment by MattisOlsson** [comment]
Thanks for reporting this mistake by me. I fixed it now and tested successfully in IE11. I just uploaded version 1.2.6 to Episerver NuGet feed and it will probably be available in the beginning of next week. If you have other DOM errors it's probably something else since I didn't see any errors when I tested.
