### ISSUE TITLE
Commerce Integration

### ISSUE THREAD

**Issue by ScottReed** [Geta/EpiCategories#2]
This is probably more of a question than a bug directly. I tried adding the category property on to a commerce item and got an issue around the meta field, I've seen a few articles here and there around getting the standard category system to work with commerce. Do you have any information on getting your one working with Commerce catalog items?

**Comment by MattisOlsson** [comment]
Hi! Sorry for the delay. Since it is basically just a content reference list I can't see why it shouldn't work, but I haven't tested it. If the native content reference list editor works (just confirmed it in Commerce 11.2), mine should work as well. You have to add the BackingType attribute to your catalog item properties though:

`[BackingType(typeof(PropertyContentReferenceList))]`
`[Categories]`
`public virtual IList<ContentReference> MyCategoryProperty { get; set; }`
