### ISSUE TITLE
Exception: Failed to load content type with name 'CategoryData' during Import

### ISSUE THREAD

**Issue by davidbuo** [Geta/EpiCategories#23]
Issues when Importing 'CategoryData' due to not having the [ContentType] attribute. Issue and solution is described in this forum [post](https://world.episerver.com/forum/developer-forum/-Episerver-75-CMS/Thread-Container/2019/8/exception-failed-to-load-content-type-with-name-categorydata-when-working-with-geta-epicategories-plugin/).

[CategoryData class](https://github.com/Geta/EpiCategories/blob/4bfdeed0ec52a6a2635dda982c05a32f1bf5604c/src/EpiCategories/CategoryData.cs)

**Comment by Tim-Schmelter** [comment]
Is this issue really fixed? If so, how? Because in the linked [post](https://world.episerver.com/forum/developer-forum/-Episerver-75-CMS/Thread-Container/2019/8/exception-failed-to-load-content-type-with-name-categorydata-when-working-with-geta-epicategories-plugin/) it was suggested to decorate CategoryData with the [ContentType] attribute, but this is not in the current code, is it? I noticed this issue during a content migration from one test environment to prod(which is crucial for go-live for a big customer this month). The exception is the same as in the linked post, but i'm using the Geta.Optimizely.Categories plugin, so i created[ another post](https://world.optimizely.com/forum/developer-forum/cms-12/thread-container/2023/11/exception-failed-to-load-content-type-with-name-categorydata-when-working-with-geta-optimizely-categories-plugin/). I have tested these export settings to no avail:

- checked/unchecked"Automatically export dependent content types" 
- Export content types:
    - Category
    - CategoriesFolder
    - CategoryRoot

As you can see, there is no CategoryData to check, which is causing this issue. But that ContentType is neither in the source db nor in the target db. So why is it causing an error on import? What can i do to fix it?
